"""add role to User

Revision ID: 75939f22bec1
Revises: d031f25d5b16
Create Date: 2022-02-09 04:47:34.289395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75939f22bec1'
down_revision = 'd031f25d5b16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_model', sa.Column('role', sa.String(length=32), server_default='simple_user', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_model', 'role')
    # ### end Alembic commands ###
